[package]
name = "gadu"
version = "0.1.0"
authors = ["Rohit Joshi <rohit.c.joshi@gmail.com>"]
edition = "2018"

[dependencies]
log="*"
url="1.7.2"
futures = "0.1.23"
mio = "0.6"
mio-uds = "0.6"
crossbeam = "0.3"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json="*"
crossbeam-channel = "0.3.2"
hashbrown = "0.1.8"
parking_lot = "0.7.1"

[features]
default=[]
ssl = ["openssl"]

[dependencies.openssl]
optional = true
version= "0.10.16"
